### ISSUE TITLE
docker build -t tinder-server . fails

### ISSUE THREAD

**Issue by 619** [MarcinMiler/tinder-clone#1]
In the dockerfile, RUN npm i -g yarn cannot be run because yarn exists already. 

Then, running docker build results in this error:

error conventional-changelog-angular@5.0.10: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
error Found incompatible module.

**Comment by 619** [comment]
This repo is a trap, do not use!

**Comment by pgnicolau** [comment]
Agreed!

**Comment by MarcinMiler** [comment]
Sorry, I don't support my old repos :shrug:
